# Generated by Django 3.2.8 on 2021-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Product name', max_length=200, verbose_name='Product name')),
                ('qty', models.IntegerField(db_column='Quantity', null=True, verbose_name='Quantity')),
                ('desc', models.CharField(db_column='Desc', max_length=200, verbose_name='Desc')),
                ('price', models.IntegerField(db_column='Price', null=True, verbose_name='Price')),
                ('img', models.CharField(db_column='IMG', max_length=500, verbose_name='IMG')),
                ('availability', models.IntegerField(db_column='Availability', null=True, verbose_name='Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tele_id', models.IntegerField(db_column='Telegramm id', unique=True, verbose_name='Telegramm id')),
                ('first_name', models.CharField(db_column='First name', max_length=200, null=True, verbose_name='First name')),
                ('last_name', models.CharField(db_column='Last name', max_length=200, null=True, verbose_name='Last name')),
                ('age', models.IntegerField(db_column='Age', null=True, verbose_name='Age')),
                ('phone', models.BigIntegerField(blank=True, db_column='Phone', default=0, null=True)),
            ],
        ),
    ]
